"""Add extended fields to Admin model

Revision ID: 0016d6727390
Revises: 7e67b55c1ae3
Create Date: 2025-09-22 11:37:58.727093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0016d6727390'
down_revision = '7e67b55c1ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_banner_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specialties', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('specialties')
        batch_op.drop_column('certifications')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('profile_banner_url')

    # ### end Alembic commands ###
