"""add admin identities

Revision ID: 0d3899eba1ae
Revises: c9b9369ac889
Create Date: 2025-08-27 12:49:21.371154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3899eba1ae'
down_revision = 'c9b9369ac889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_user_id', sa.String(length=191), nullable=False),
    sa.Column('email_at_auth_time', sa.String(length=191), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_admin_identity_provider_uid')
    )
    with op.batch_alter_table('admin_identities', schema=None) as batch_op:
        batch_op.create_index('ix_admin_identity_email_provider', ['email_at_auth_time', 'provider'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_identity_email_provider')

    op.drop_table('admin_identities')
    # ### end Alembic commands ###
