"""add exercise fields to workout_sessions

Revision ID: 711d9e360504
Revises: 9dc079b958a2
Create Date: 2025-08-11 18:36:22.258237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711d9e360504'
down_revision = '9dc079b958a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight_lbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('weight_lbs')
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')
        batch_op.drop_column('exercise_name')

    # ### end Alembic commands ###
