"""add charting fields to workout_sessions

Revision ID: 9dc079b958a2
Revises: 8521ac27aee4
Create Date: 2025-08-11 16:02:01.411315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc079b958a2'
down_revision = '8521ac27aee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workout_type', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('workout_date', sa.DateTime(), nullable=True),
    sa.Column('day_of_week', sa.String(length=3), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sessions')
    op.drop_table('login_sessions')
    # ### end Alembic commands ###
