"""Add cascade delete to workout_sessions.user_id

Revision ID: 9ea397ece27f
Revises: cd6223bf24c9
Create Date: 2025-08-16 22:28:29.502341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea397ece27f'
down_revision = 'cd6223bf24c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('workout_sessions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workout_sessions_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
