"""Add admin_id to face_embeddings

Revision ID: aaeed6f273b9
Revises: c70e87a191e8
Create Date: 2025-10-07 10:28:43.449883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaeed6f273b9'
down_revision = 'c70e87a191e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_faces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.UUID(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_face_embeddings_admin_id'), ['admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_face_embeddings_admin_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('admin_id')

    op.drop_table('admin_faces')
    # ### end Alembic commands ###
