"""Add social media fields to Admin model

Revision ID: af145665025b
Revises: d74c42ec94b2
Create Date: 2025-09-24 10:37:03.615791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af145665025b'
down_revision = 'd74c42ec94b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('tiktok')
        batch_op.drop_column('youtube')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')

    # ### end Alembic commands ###
