"""remove unique constraint from stripe_price_id

Revision ID: c9b9369ac889
Revises: 6254983350a9
Create Date: 2025-08-20 11:46:37.520616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b9369ac889'
down_revision = '6254983350a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('membership_plans_stripe_price_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('membership_plans_stripe_price_id_key'), ['stripe_price_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
