"""Add stripe_price_id to membership plans

Revision ID: cd6223bf24c9
Revises: 711d9e360504
Create Date: 2025-08-16 21:56:58.621659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6223bf24c9'
down_revision = '711d9e360504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_price_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_membership_plan_id'), ['membership_plan_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('users_membership_plan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'membership_plans', ['membership_plan_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_membership_plan_id_fkey'), 'membership_plans', ['membership_plan_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_users_membership_plan_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_price_id')

    # ### end Alembic commands ###
