"""Add schedule fields to Admin model (days, times, group, virtual_session)

Revision ID: d74c42ec94b2
Revises: 0016d6727390
Create Date: 2025-09-22 13:36:25.258996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74c42ec94b2'
down_revision = '0016d6727390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('times', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('group', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('virtual_session', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('virtual_session')
        batch_op.drop_column('group')
        batch_op.drop_column('times')
        batch_op.drop_column('days')

    # ### end Alembic commands ###
