"""soft delete + hidden flags for conversations/messages

Revision ID: f2e5db7a1217
Revises: 4ad31fb87204
Create Date: 2025-09-04 20:02:13.689894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e5db7a1217'
down_revision = '4ad31fb87204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden_for_user_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('hidden_for_admin_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_for_user_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_for_admin_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('moderation_deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('moderation_deleted_by_admin_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'admins', ['moderation_deleted_by_admin_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('moderation_deleted_by_admin_id')
        batch_op.drop_column('moderation_deleted_at')
        batch_op.drop_column('deleted_for_admin_at')
        batch_op.drop_column('deleted_for_user_at')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('hidden_for_admin_at')
        batch_op.drop_column('hidden_for_user_at')

    # ### end Alembic commands ###
